{"name": "test_login_with_error_keyword", "status": "failed", "statusDetails": {"message": "AssertionError: assert '帐号或密码错误。' in '访问被拒绝，你可能没有权限或未登录。'", "trace": "self = <selenium_test.Test_Selenium.Test_Selenium object at 0x03A238B0>\n\n    def test_login_with_error_keyword(self):\n        self.test_hogwarts()\n        self.driver.find_element(By.CSS_SELECTOR,\"input[type='email']\").send_keys(\"123456\")\n        self.driver.find_element(By.CSS_SELECTOR, \"input[type='password']\").send_keys(\"123456\")\n        self.driver.find_element(By.CSS_SELECTOR, \"input[type='submit']\").click()\n        str = self.driver.find_element(By.CSS_SELECTOR, \"div[class='alert alert-danger']\").text\n>       assert \"帐号或密码错误。\" in str\nE       AssertionError: assert '帐号或密码错误。' in '访问被拒绝，你可能没有权限或未登录。'\n\nselenium_test\\Test_Selenium.py:48: AssertionError"}, "start": 1569159575432, "stop": 1569159577117, "uuid": "9a17619b-fce2-4d5a-8dbb-03bb2189e99a", "historyId": "faf5c76c15c8012fbf7e09b8d5afb48f", "testCaseId": "cb01bb63122ad96c198054eda439cd76", "fullName": "selenium_test.Test_Selenium.Test_Selenium#test_login_with_error_keyword", "labels": [{"name": "parentSuite", "value": "selenium_test"}, {"name": "suite", "value": "Test_Selenium"}, {"name": "subSuite", "value": "Test_Selenium"}, {"name": "host", "value": "BF-201801061158"}, {"name": "thread", "value": "916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "selenium_test.Test_Selenium"}]}